"""Compatibility facade for action services.

This module preserves legacy import paths while delegating implementations to
smaller service modules.
"""

from services.action_lifecycle_service import (
    create_action,
    log_action_event,
    log_coaching_lifecycle_entry,
    log_recognition_event,
    mark_action_deprioritized,
    mark_action_escalated,
    mark_action_in_progress,
    mark_action_resolved,
    mark_action_transferred,
    reopen_action,
    refresh_action_statuses,
    run_all_triggers,
    trigger_follow_up_due,
    trigger_ignored_high_performer,
    trigger_repeat_no_improvement,
    trigger_repeated_low_performance,
)
from services.action_metrics_service import (
    _recent_action_outcomes,
    get_manager_outcome_stats,
    get_product_success_metrics,
)
from services.action_query_service import (
    _below_goal_streak,
    _build_next_step,
    _extract_row_dept,
    _extract_row_emp_id,
    _extract_row_name,
    _extract_row_uph,
    _history_by_emp,
    _open_actions_by_emp,
    _parse_date,
    _queue_state,
    _recent_average_uph,
    _safe_float,
    build_ignored_high_performers,
    build_recent_outcomes,
    build_repeat_offenders,
    build_today_screen_payload,
    get_action_history,
    get_employee_action_timeline,
    get_employee_actions,
    get_open_actions,
    get_overdue_actions,
    normalize_emp_id,
)
from services.action_recommendation_service import (
    get_action_recommendation,
    get_ignored_high_performers,
    get_repeat_offenders,
)

__all__ = [
    "_below_goal_streak",
    "_build_next_step",
    "_extract_row_dept",
    "_extract_row_emp_id",
    "_extract_row_name",
    "_extract_row_uph",
    "_history_by_emp",
    "_open_actions_by_emp",
    "_parse_date",
    "_queue_state",
    "_recent_action_outcomes",
    "_recent_average_uph",
    "_safe_float",
    "build_ignored_high_performers",
    "build_recent_outcomes",
    "build_repeat_offenders",
    "build_today_screen_payload",
    "create_action",
    "get_action_history",
    "get_action_recommendation",
    "get_employee_action_timeline",
    "get_employee_actions",
    "get_ignored_high_performers",
    "get_manager_outcome_stats",
    "get_open_actions",
    "get_overdue_actions",
    "get_product_success_metrics",
    "get_repeat_offenders",
    "log_action_event",
    "log_coaching_lifecycle_entry",
    "log_recognition_event",
    "mark_action_deprioritized",
    "mark_action_escalated",
    "mark_action_in_progress",
    "mark_action_resolved",
    "mark_action_transferred",
    "normalize_emp_id",
    "reopen_action",
    "refresh_action_statuses",
    "run_all_triggers",
    "trigger_follow_up_due",
    "trigger_ignored_high_performer",
    "trigger_repeat_no_improvement",
    "trigger_repeated_low_performance",
]
